---
- hosts: localhost
  user: root      
  vars_files:
    - vars.yml
  become: yes
  tasks:
    - include: tasks/provisionJenkins.yml

- hosts: localhost
  user: root      
  vars_files:
    - vars.yml
  become: yes
  tasks:
    - include: tasks/job.yml

- hosts: localhost
  user: root      
  vars_files:
    - vars.yml
  become: yes
  tasks:
    - include: tasks/job2.yml
