  - name: get admin password
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: adminPassword
    
  - name: Debug
    debug:
      msg: "{{adminPassword.stdout}}"

  - name: Get Jenkins crumb
    uri:
      user: admin
      password: "{{adminPassword.stdout}}"
      force_basic_auth: yes
      url: "http://127.0.0.1:8080/crumbIssuer/api/json"
      return_content: yes
    register: jenkins_crumb
    until: jenkins_crumb.content.find('Please wait while Jenkins is getting ready to work') == -1
    retries: 10
    delay: 5

  - name: Set crumb token
    set_fact:
      jenkins_crumb_token: "{{ jenkins_crumb.json.crumbRequestField }}={{ jenkins_crumb.json.crumb }}"

  - name: debug crumb
    debug:
      msg: "{{jenkins_crumb.json.crumb}}"

  - name: Get list of jobs
    uri:
      user: admin
      password: "{{adminPassword.stdout}}"
      force_basic_auth: yes
      url: "http://127.0.0.1:8080/api/json?tree=jobs[name]"
      return_content: yes
    register: jenkins_jobs
    until: jenkins_jobs.content.find('Please wait while Jenkins is getting ready to work') == -1
    retries: 10
    delay: 5

  - name: Check if build_provision itrust job exists
    set_fact:
      jenkins_build_provision_job_exists: "{{ 'itrust_build_provision' in (jenkins_jobs.content|from_json).jobs|map(attribute='name')|list }}"

  - name: Create build_provision itrust job
    uri:
      user: admin
      password: "{{adminPassword.stdout}}"
      force_basic_auth: yes
      url: "http://127.0.0.1:8080/createItem?name=itrust_build_provision&{{ jenkins_crumb_token }}"
      method: POST
      headers:
        Content-Type: application/xml
      body: "{{ lookup('file','itrust_job1/config.xml') }}"
    register: jenkins_build_provision_job_updated
    when: not jenkins_build_provision_job_exists

  - name: Run build_provision job
    uri:
      user: admin
      password: "{{adminPassword.stdout}}"
      force_basic_auth: yes
      url: "http://127.0.0.1:8080/job/itrust_build_provision/build?token=build_itrust"
      method: POST
      headers:
        Jenkins-Crumb : "{{ jenkins_crumb.json.crumb }}"
      status_code: 201


